name: Get Merge and Previous Commit

on:
  pull_request:
    types: [closed]

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits

      - name: Get Merge Commit SHA
        run: echo "Merge Commit SHA: ${{ github.sha }}"

      - name: Get Previous Commit SHA
        run: |
          PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
          echo "Previous Commit SHA: $PREVIOUS_COMMIT"
