name: Get Previous Commit SHA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Previous Commit SHA
      id: get_previous_sha
      run: echo "PREVIOUS_SHA=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

    - name: Use Previous Commit SHA
      run: echo "Previous Commit SHA is $PREVIOUS_SHA"