name: Get Updated Files

on:
  push:
    branches:
      - main

jobs:
  get-updated-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the last two commits

      - name: Retrieve Changed Files
        id: files
        uses: masesgroup/retrieve-changed-files@v3
        with:
          format: 'json' 
      - run: |
          echo ${{ steps.files.outputs.all }} > merged_files.txt
          readarray -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
            for added_modified_file in "${added_modified_files[@]}"; do
                echo "Added or Modified File ${added_modified_file}."
          done          
          readarray -t removed_files < <(printf '%s,' '${{ steps.files.outputs.removed }}')
            for removed_file in "${removed_files[@]}"; do
                echo "Deleted File ${removed_file}."
          done
          readarray -t renamed_files < <(printf '%s,' '${{ steps.files.outputs.renamed }}')
            for renamed_file in "${renamed_files[@]}"; do
                echo "Renamed File ${renamed_file}."
          done

      - name: Log file changes
        id: LogFileChanges
        run: |     
          # Create or update the log file
          LOG_FILE="file_changes.log"
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
        
          for file in ${{ steps.files.outputs.changed_files }}; do
            echo "$DATE - CHANGED - $file" >> $LOG_FILE
          done
        
          for file in ${{ steps.files.outputs.added_files }}; do
            echo "$DATE - ADDED - $file" >> $LOG_FILE
          done
        
          for file in ${{ steps.files.outputs.deleted_files }}; do
            echo "$DATE - DELETED - $file" >> $LOG_FILE
          done
        
          # Commit and push the log file
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add $LOG_FILE
          git commit -m "Update file changes log"
          git push origin HEAD:${{ github.head_ref }}
