name: Capture Copilot Analysis of Merged Files

on:
  pull_request:
    types: [closed]

jobs:
  analyze-merged-files:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get merge commit and previous commit
      id: get-commits
      run: |
        # Get the merge commit
        MERGE_COMMIT=$(git rev-parse HEAD)
        echo "Merge Commit: $MERGE_COMMIT"

        # Get the previous commit
        #PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
        PREVIOUS_COMMIT=$(git log --merges -n 1 --pretty=format:%H)
        echo "Previous Commit: $PREVIOUS_COMMIT"

        # Set outputs
        echo "::set-output name=merge_commit::$MERGE_COMMIT"
        echo "::set-output name=previous_commit::$PREVIOUS_COMMIT"

    - name: Compare commits and get changed files
      id: compare-commits
      run: |
        # Get the merge commit and previous commit from the previous step
        MERGE_COMMIT=${{ steps.get-commits.outputs.merge_commit }}
        PREVIOUS_COMMIT=${{ steps.get-commits.outputs.previous_commit }}

        # Compare commits and get changed files
        git diff --name-only $PREVIOUS_COMMIT $MERGE_COMMIT > merged_files.txt
        echo "Changed Files: $CHANGED_FILES"

    - name: Display merged files
      run: |
        echo "The following files were merged:"
        cat merged_files.txt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Generate Copilot analysis summaries
      id: copilot-summaries
      run: |
        python generate_copilot_summaries.py merged_files.txt ${{ github.repository }} ${{ github.sha }}

    - name: Display Copilot summaries
      run: |
        echo "Copilot analysis summaries:"
        cat copilot_summaries.txt

    - name: Upload summaries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: copilot-summaries
        path: copilot_summaries.txt