name: Capture Copilot Analysis of Merged Files

on:
  pull_request:
    types: [closed]

jobs:
  analyze-merged-files:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get list of merged files
      id: merged-files
      run: |
        git fetch origin
        git checkout ${{ github.event.pull_request.base.ref }}
        git pull
        git diff --name-only ${{ github.sha }} HEAD^ > merged_files.txt

    - name: Display merged files
      run: |
        echo "The following files were merged:"
        cat merged_files.txt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Generate Copilot analysis summaries
      id: copilot-summaries
      run: |
        python generate_copilot_summaries.py merged_files.txt ${{ github.repository }} ${{ github.sha }}

    - name: Display Copilot summaries
      run: |
        echo "Copilot analysis summaries:"
        cat copilot_summaries.txt

    - name: Upload summaries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: copilot-summaries
        path: copilot_summaries.txt