name: Scan Updated Files For Bad Links

on:
  push:
    branches:
      - main

jobs:
  scan-files:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the last two commits

      - name: Get list of changed files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "::set-output name=files::$(cat changed_files.txt | tr '\n' ',')"

      - name: Run PowerShell script on changed files
        run: |
          $changedFiles = "${{ steps.changed-files.outputs.files }}".Split(',')
          foreach ($file in $changedFiles) {
            Write-Host "Scanning file: $file"
            # Call your PowerShell script here
            .\md-link-checker.ps1 $file
          }
        shell: pwsh