name: Write File

on:
  push:
    branches:
      - main
      
jobs:
  create_date_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate date variable
      run: |
        DATE=$(date '+%Y-%m-%d')
        FILE_NAME="file_${DATE}.txt"
        echo "Creating file: $FILE_NAME"
        echo "This file was created on $DATE" > $FILE_NAME

    - name: Commit and push changes
      run: |
        git config --global user.name 'SimonF-MSFT'
        git config --global user.email 'simonfacer@microsoft.com'
        git add file_*.txt
        git commit -m "Add file with date in name"
        git push